# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [1]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == "zeros":
        return np.zeros(shape)

    elif mode == "ones":
        return np.ones(shape)

    elif mode == "full":
        if value is None:
            raise ValueError("value is required for 'full' mode")
        return np.full(shape, value)

    elif mode == "identity":
        return np.eye(shape)

    else:
        raise ValueError("Invalid mode. Use 'zeros', 'ones', 'full', or 'identity'")

In [2]:
print(array_factory("zeros", (2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [4]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to NumPy arrays
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Change the shape of arr1
        reshaped_arr1 = arr1.reshape(new_shape)

        # Vertical Stacking
        # Both arrays must have the same number of columns
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Handle reshape or stacking errors
        raise ValueError(f"Company-grade Error: {e}")

part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [7]:
import numpy as np


def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold)
    and replaces them with a new value.
    """

    # 1. Convert input to a NumPy array
    arr = np.array(arr)

    # 2. Define the condition
    condition = arr >= threshold

    # 3. Apply modification using np.where()
    modified_arr = np.where(
        condition,
        replacement_value,
        arr
    )

    return modified_arr

TestCase

In [12]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])