In [1]:
import numpy as np

print(np.__version__)

1.25.2


In [7]:
v1 =np.array([10,6,7])
v2 =np.array([3,5,12])
v3= np.array(5)

print(v1.shape)
print(v2)
print(v3.ndim)

(3,)
[ 3  5 12]
0


In [8]:
class Student:
    def __init__(self, name, age) -> None:
        self.name= name
        self.age= age
    #@property
    def name(self):
        return f'{self._name}'

In [9]:
s1=Student("Rawan",21)
s1.name

'Rawan'

In [11]:
vec= np.array([1,2,3,4,5,6])
mat= vec.reshape(2,3)
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
vec= np.array([1,2,3,4,5,6])
#mat= vec.reshape((vec.shape[0]))
mat= vec
mat

array([1, 2, 3, 4, 5, 6])

In [16]:
def array_reshape(arr, row= -1, cols= -1):
    try:
        arr= np.array(arr)
        return arr.reshape((row, cols))
    except Exception as e:
        raise ValueError("Invalid Reshape Operation:{e}")

In [17]:
vec= [1,2,3,4,5,6]
print(array_reshape(vec,2,3))

[[1 2 3]
 [4 5 6]]
